<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<div class="block jqueryui-getter-setter">
    <h2><?= __('Getting, and setting widget values.'); ?></h2>
    <p><?= __('See console for extra output.'); ?></p>
    <div class="slider"></div>
</div>

<script type="text/x-magento-init">
    {
        ".jqueryui-getter-setter .slider": {
            "Koz_JqueryUI/js/getter-setter": {}
        }
    }
</script>


